name: Build and test
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: poetry
        uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: 1.1.2
      - name: build
        run: |
          make all
      - name: Quay login
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}
      - name: push images
        run: |
          make push